### ISSUE TITLE
Make timeout configurable

### ISSUE THREAD

**Issue by ykk1991** [entur/gbfs-loader-java#29]
Hello,

I had connection problems when retrieving data :
`Error (bad connection) reading GBFS feed from xxx`
`java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1104)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.entur.gbfs.HttpUtils.getData(HttpUtils.java:48)
	at org.entur.gbfs.HttpUtils.getData(HttpUtils.java:62)
	at org.entur.gbfs.GbfsLoader.fetchFeed(GbfsLoader.java:227)
	at org.entur.gbfs.GbfsLoader.access$700(GbfsLoader.java:31)
	at org.entur.gbfs.GbfsLoader$GBFSFeedUpdater.fetchData(GbfsLoader.java:278)
	at org.entur.gbfs.GbfsLoader$GBFSFeedUpdater.access$300(GbfsLoader.java:253)
	at org.entur.gbfs.GbfsLoader.update(GbfsLoader.java:197)`

This happened from time to time but quite often. It's not possible to override the value of TIMEOUT_CONNECTION which I suspect the origin of the connection problem.

Is there any way to fix it? A new version in the near futur ?

Thanks a lot for your help.

**Comment by testower** [comment]
Thanks for raising this issue. This sounds like a reasonable feature - would you care to submit a PR on it?

**Comment by testower** [comment]
Thanks for the contribution. I will make a new release shortly that will also include final 2.3 support.
